// Industry Playbooks, defaults the autonomous content engine runs on.
// Each playbook seeds 7 starter content ideas and provides sensible brand defaults.

export type PlaybookIdeaTemplate = {
  dayOffset: number; // 0 = today, 1 = tomorrow ...
  title: string;
  prompt: string;
  category: string; // matches contentCategories ids
  idea_type?: "single" | "carousel" | "campaign";
};

export type IndustryPlaybook = {
  id: string;
  name: string;
  emoji: string;
  tagline: string;
  sample: string; // sample weekly cadence
  defaultVibe: string;
  defaultTone: string;
  defaultPersonality: string[];
  defaultPalette: { primary: string; secondary: string; accent: string };
  weeklyTemplate: PlaybookIdeaTemplate[];
};

const t = (
  dayOffset: number,
  title: string,
  prompt: string,
  category: string,
  idea_type: "single" | "carousel" | "campaign" = "single",
): PlaybookIdeaTemplate => ({ dayOffset, title, prompt, category, idea_type });

export const INDUSTRY_PLAYBOOKS: IndustryPlaybook[] = [
  {
    id: "restaurants",
    name: "Restaurants & Cafés",
    emoji: "🍽️",
    tagline: "Daily specials, weekend hype, regular-customer love.",
    sample: "Mon special · Wed behind-the-kitchen · Fri weekend hype · Sun gratitude post",
    defaultVibe: "Warm",
    defaultTone: "Warm and inviting, a little playful",
    defaultPersonality: ["Warm", "Approachable", "Playful"],
    defaultPalette: { primary: "#B8462E", secondary: "#F4E8D8", accent: "#2B2D33" },
    weeklyTemplate: [
      t(0, "Today's special", "A bold mouth-watering hero shot poster announcing today's special dish with price.", "promotion"),
      t(1, "Behind the kitchen", "A cinematic behind-the-scenes shot of the chef plating, captioned to build trust.", "behind_the_scenes"),
      t(2, "Customer love", "A clean testimonial card quoting a happy regular customer.", "social_proof"),
      t(3, "Did you know?", "An educational micro-fact about one of our signature ingredients.", "education"),
      t(4, "Weekend hype", "A vibrant weekend-vibes post inviting people to book a table.", "promotion"),
      t(5, "Order online", "A clean product-style post with a clear ORDER NOW call to action.", "promotion"),
      t(6, "Thank you", "A warm gratitude post thanking the community for the week.", "community"),
    ],
  },
  {
    id: "beauty",
    name: "Beauty & Salons",
    emoji: "💅",
    tagline: "Before/afters, booking nudges, treatment education.",
    sample: "Mon transformation · Wed treatment 101 · Fri booking nudge · Sun glow inspiration",
    defaultVibe: "Luxury",
    defaultTone: "Soft, confident, aspirational",
    defaultPersonality: ["Sophisticated", "Warm", "Inspiring"],
    defaultPalette: { primary: "#C4993B", secondary: "#FAF8F5", accent: "#2B2D33" },
    weeklyTemplate: [
      t(0, "Transformation Tuesday", "A clean side-by-side before/after style poster of a recent client treatment.", "social_proof"),
      t(1, "Treatment 101", "An educational explainer of one signature treatment and its benefit.", "education"),
      t(2, "Glow inspiration", "An aspirational lifestyle post showing the after-feeling, not the service.", "inspiration"),
      t(3, "Meet the artist", "A warm portrait-style post introducing one of the team members.", "behind_the_scenes"),
      t(4, "Booking nudge", "A clear, gentle reminder post with a BOOK NOW call to action for the weekend.", "promotion"),
      t(5, "Care tip", "A short take-home care tip educational post.", "education"),
      t(6, "Client love", "A testimonial card from a recent happy client.", "social_proof"),
    ],
  },
  {
    id: "fitness",
    name: "Fitness & Wellness",
    emoji: "💪",
    tagline: "Class promos, transformation stories, motivation Mondays.",
    sample: "Mon motivation · Wed class promo · Fri transformation · Sun recovery",
    defaultVibe: "Bold",
    defaultTone: "High-energy, encouraging, no-nonsense",
    defaultPersonality: ["Energetic", "Bold", "Inspiring"],
    defaultPalette: { primary: "#16A34A", secondary: "#0F172A", accent: "#FACC15" },
    weeklyTemplate: [
      t(0, "Motivation Monday", "A bold typographic motivation poster with a punchy one-liner.", "inspiration"),
      t(1, "Class promo", "A high-energy poster promoting this week's signature class with day & time.", "promotion"),
      t(2, "Form check", "A short educational tip post about one common training mistake.", "education"),
      t(3, "Transformation", "A respectful before/after style post celebrating a member's progress.", "social_proof"),
      t(4, "Weekend challenge", "A weekend mini-challenge post inviting members to participate.", "community"),
      t(5, "Recovery tip", "A calmer post about rest, mobility, or recovery.", "education"),
      t(6, "Member spotlight", "A warm spotlight post on one community member.", "community"),
    ],
  },
  {
    id: "retail",
    name: "Boutique Retail",
    emoji: "🛍️",
    tagline: "New arrivals, styling tips, sale countdowns.",
    sample: "Mon new in · Wed style guide · Fri offer · Sun lookbook",
    defaultVibe: "Minimal",
    defaultTone: "Crisp, stylish, confident",
    defaultPersonality: ["Sophisticated", "Bold", "Approachable"],
    defaultPalette: { primary: "#1E293B", secondary: "#FAF8F5", accent: "#C4993B" },
    weeklyTemplate: [
      t(0, "New in", "A clean editorial-style poster announcing a new arrival product.", "product_launch"),
      t(1, "Style this", "A styling tip post showing 3 ways to wear / use a featured product.", "education", "carousel"),
      t(2, "Customer fit", "A user-generated style testimonial card.", "social_proof"),
      t(3, "Limited offer", "A bold sale or limited-offer poster with clear deadline.", "promotion"),
      t(4, "Lookbook", "A moody lookbook hero image showcasing the season's mood.", "inspiration"),
      t(5, "Restock alert", "A clean alert-style post about a restocked bestseller.", "promotion"),
      t(6, "Thank-you note", "A warm thank-you post to weekend shoppers.", "community"),
    ],
  },
  {
    id: "services",
    name: "Professional Services",
    emoji: "💼",
    tagline: "Authority posts, client wins, lead-gen offers.",
    sample: "Mon insight · Wed case study · Fri offer · Sun thought-leadership",
    defaultVibe: "Corporate",
    defaultTone: "Confident, expert, plain-spoken",
    defaultPersonality: ["Authoritative", "Trustworthy", "Inspiring"],
    defaultPalette: { primary: "#1D4ED8", secondary: "#F8FAFC", accent: "#0F172A" },
    weeklyTemplate: [
      t(0, "Insight of the week", "A bold typographic insight post sharing one sharp opinion in our field.", "thought_leadership"),
      t(1, "Client win", "A clean case-study card highlighting a recent client outcome with a stat.", "social_proof"),
      t(2, "How we work", "An educational explainer of one piece of our process.", "education", "carousel"),
      t(3, "Myth vs fact", "A myth-busting post for our industry.", "education"),
      t(4, "Free consult offer", "A clean lead-gen poster offering a free consultation with a clear CTA.", "promotion"),
      t(5, "Tool we love", "A short post recommending a tool or framework we use.", "thought_leadership"),
      t(6, "Team note", "A warm post introducing the team or a team milestone.", "community"),
    ],
  },
  {
    id: "saas",
    name: "Software & SaaS",
    emoji: "💻",
    tagline: "Feature drops, product education, customer wins.",
    sample: "Mon insight · Wed feature drop · Fri case study · Sun roadmap tease",
    defaultVibe: "Modern",
    defaultTone: "Sharp, clear, confident, founder-voice",
    defaultPersonality: ["Innovative", "Trustworthy", "Bold"],
    defaultPalette: { primary: "#6366F1", secondary: "#0F172A", accent: "#22D3EE" },
    weeklyTemplate: [
      t(0, "Insight of the week", "A bold typographic post sharing one sharp opinion about our industry.", "thought_leadership"),
      t(1, "Feature spotlight", "A clean product-style poster highlighting one feature with a benefit-led headline.", "product_launch"),
      t(2, "How it works", "An educational explainer post showing how to use a key part of the product.", "education", "carousel"),
      t(3, "Customer win", "A case-study card with a clear outcome stat from a happy customer.", "social_proof"),
      t(4, "Free trial nudge", "A clean conversion poster inviting people to try the product free with a clear CTA.", "promotion"),
      t(5, "Tip of the week", "A short power-user tip post.", "education"),
      t(6, "Roadmap tease", "A teaser post hinting at what is shipping next.", "thought_leadership"),
    ],
  },
  {
    id: "ecommerce",
    name: "E-commerce & DTC",
    emoji: "📦",
    tagline: "Product launches, social proof, conversion offers.",
    sample: "Mon launch · Wed UGC · Fri offer · Sun lifestyle",
    defaultVibe: "Modern",
    defaultTone: "Punchy, benefit-led, confident",
    defaultPersonality: ["Bold", "Approachable", "Inspiring"],
    defaultPalette: { primary: "#0F172A", secondary: "#FAF8F5", accent: "#EF4444" },
    weeklyTemplate: [
      t(0, "New drop", "A bold editorial poster announcing a new product drop.", "product_launch"),
      t(1, "Why customers love it", "A clean testimonial card with a customer quote and star rating.", "social_proof"),
      t(2, "How to use it", "A practical how-to post showing the product in action.", "education", "carousel"),
      t(3, "Founder note", "A warm founder-voice post sharing the story behind a product.", "behind_the_scenes"),
      t(4, "Limited offer", "A bold sale poster with countdown energy and a clear CTA.", "promotion"),
      t(5, "Lifestyle moment", "A moody lifestyle hero shot showing the product in real life.", "inspiration"),
      t(6, "Bestseller restock", "A clean alert post about a restocked bestseller.", "promotion"),
    ],
  },
  {
    id: "realestate",
    name: "Real Estate & Property",
    emoji: "🏠",
    tagline: "New listings, market insights, agent authority.",
    sample: "Mon market tip · Wed new listing · Fri open house · Sun sold",
    defaultVibe: "Luxury",
    defaultTone: "Confident, expert, aspirational",
    defaultPersonality: ["Authoritative", "Sophisticated", "Trustworthy"],
    defaultPalette: { primary: "#0F172A", secondary: "#FAF8F5", accent: "#C4993B" },
    weeklyTemplate: [
      t(0, "Market insight", "A bold typographic stat-card sharing one market insight for buyers or sellers.", "thought_leadership"),
      t(1, "New listing", "A clean editorial-style poster announcing a new property listing with key stats.", "product_launch"),
      t(2, "Buyer tip", "An educational tip post for first-time buyers.", "education"),
      t(3, "Open house invite", "A bold invite poster for this weekend's open house with date and time.", "promotion"),
      t(4, "Sold!", "A celebratory post announcing a recently sold property.", "social_proof"),
      t(5, "Neighbourhood spotlight", "A warm post highlighting one neighbourhood we serve.", "community"),
      t(6, "Meet your agent", "A trust-building portrait post introducing the agent.", "behind_the_scenes"),
    ],
  },
  {
    id: "education",
    name: "Education & Coaching",
    emoji: "🎓",
    tagline: "Lessons, student wins, enrolment nudges.",
    sample: "Mon lesson · Wed student win · Fri enrolment · Sun mindset",
    defaultVibe: "Friendly",
    defaultTone: "Encouraging, clear, expert",
    defaultPersonality: ["Inspiring", "Trustworthy", "Warm"],
    defaultPalette: { primary: "#1D4ED8", secondary: "#FAF8F5", accent: "#FACC15" },
    weeklyTemplate: [
      t(0, "Lesson of the week", "A clean educational post teaching one focused concept in plain English.", "education"),
      t(1, "Student win", "A celebratory testimonial card from a student outcome.", "social_proof"),
      t(2, "Common mistake", "A myth-busting post correcting one common mistake learners make.", "education"),
      t(3, "Mindset post", "An inspirational typographic post with a punchy one-liner.", "inspiration"),
      t(4, "Enrolment open", "A bold poster announcing open enrolment with a clear CTA.", "promotion"),
      t(5, "Behind the scenes", "A warm behind-the-scenes look at the teaching team.", "behind_the_scenes"),
      t(6, "Q&A", "A community post inviting questions from learners.", "community"),
    ],
  },
  {
    id: "healthcare",
    name: "Healthcare & Wellness Clinics",
    emoji: "🩺",
    tagline: "Patient education, trust-building, appointment nudges.",
    sample: "Mon health tip · Wed myth-bust · Fri booking nudge · Sun team",
    defaultVibe: "Calm",
    defaultTone: "Warm, expert, reassuring",
    defaultPersonality: ["Trustworthy", "Warm", "Authoritative"],
    defaultPalette: { primary: "#0E7490", secondary: "#F8FAFC", accent: "#22C55E" },
    weeklyTemplate: [
      t(0, "Health tip", "A clean educational post sharing one practical health tip in plain English.", "education"),
      t(1, "Myth vs fact", "A myth-busting post correcting a common health misconception.", "education"),
      t(2, "Patient story", "A respectful testimonial card from a patient outcome.", "social_proof"),
      t(3, "Meet the team", "A warm portrait post introducing one of the practitioners.", "behind_the_scenes"),
      t(4, "Book an appointment", "A clean nudge poster with a clear BOOK NOW call to action.", "promotion"),
      t(5, "Did you know?", "An educational micro-fact post about a service we offer.", "education"),
      t(6, "Community thank-you", "A warm thank-you post to the patient community.", "community"),
    ],
  },
  {
    id: "events",
    name: "Events & Hospitality",
    emoji: "🎉",
    tagline: "Event hype, ticket nudges, recap reels.",
    sample: "Mon teaser · Wed lineup · Fri ticket nudge · Sun recap",
    defaultVibe: "Bold",
    defaultTone: "High-energy, inviting, FOMO-inducing",
    defaultPersonality: ["Energetic", "Bold", "Inspiring"],
    defaultPalette: { primary: "#7C3AED", secondary: "#0F172A", accent: "#F59E0B" },
    weeklyTemplate: [
      t(0, "Save the date", "A bold poster announcing the upcoming event with date and venue.", "promotion"),
      t(1, "Lineup reveal", "An editorial-style post revealing speakers / artists / hosts.", "product_launch"),
      t(2, "Behind the scenes", "A behind-the-scenes setup shot building anticipation.", "behind_the_scenes"),
      t(3, "Last tickets", "A bold scarcity poster about limited tickets remaining.", "promotion"),
      t(4, "Why you should come", "A short benefit-led post with 3 reasons to attend.", "education", "carousel"),
      t(5, "Recap moment", "A vibrant recap post from a previous event.", "social_proof"),
      t(6, "Thank you", "A warm community thank-you to attendees.", "community"),
    ],
  },
  {
    id: "creators",
    name: "Creators & Personal Brands",
    emoji: "🎙️",
    tagline: "Thought leadership, story posts, audience building.",
    sample: "Mon insight · Wed story · Fri offer · Sun reflection",
    defaultVibe: "Modern",
    defaultTone: "Personal, sharp, opinionated",
    defaultPersonality: ["Bold", "Inspiring", "Authentic"],
    defaultPalette: { primary: "#0F172A", secondary: "#FAF8F5", accent: "#F43F5E" },
    weeklyTemplate: [
      t(0, "Hot take", "A bold typographic post sharing one sharp opinion.", "thought_leadership"),
      t(1, "Story post", "A personal-voice post sharing a short story with a lesson.", "behind_the_scenes"),
      t(2, "Quick tip", "A short educational tip post.", "education"),
      t(3, "Frameworks", "A clean carousel breaking down a framework or method.", "education", "carousel"),
      t(4, "Offer drop", "A clean conversion post promoting our offer with a clear CTA.", "promotion"),
      t(5, "Behind the scenes", "A casual behind-the-scenes look at how we work.", "behind_the_scenes"),
      t(6, "Sunday reflection", "A reflective inspirational post.", "inspiration"),
    ],
  },
  {
    id: "nonprofit",
    name: "Nonprofit & Community",
    emoji: "🤝",
    tagline: "Mission stories, donor nudges, volunteer love.",
    sample: "Mon mission · Wed impact stat · Fri donate · Sun volunteer",
    defaultVibe: "Warm",
    defaultTone: "Hopeful, sincere, mission-driven",
    defaultPersonality: ["Warm", "Trustworthy", "Inspiring"],
    defaultPalette: { primary: "#15803D", secondary: "#FAF8F5", accent: "#F59E0B" },
    weeklyTemplate: [
      t(0, "Our mission", "A bold typographic post stating our mission in one clear sentence.", "thought_leadership"),
      t(1, "Impact stat", "A clean stat-card showing one piece of recent impact data.", "social_proof"),
      t(2, "Story from the field", "A warm story post highlighting one beneficiary or moment.", "behind_the_scenes"),
      t(3, "Volunteer spotlight", "A grateful spotlight post on a volunteer.", "community"),
      t(4, "Donate today", "A clean conversion poster with a clear DONATE NOW call to action.", "promotion"),
      t(5, "Education post", "An educational post about the issue we work on.", "education"),
      t(6, "Thank you", "A warm thank-you post to the community.", "community"),
    ],
  },
  {
    id: "general",
    name: "Other small business",
    emoji: "✨",
    tagline: "A balanced weekly mix to keep your brand visible.",
    sample: "Mon promo · Wed education · Fri social proof · Sun community",
    defaultVibe: "Minimal",
    defaultTone: "Friendly and clear",
    defaultPersonality: ["Approachable", "Trustworthy", "Warm"],
    defaultPalette: { primary: "#2B2D33", secondary: "#FAF8F5", accent: "#C4993B" },
    weeklyTemplate: [
      t(0, "What we do", "A clean intro poster explaining what our business does in one sentence.", "education"),
      t(1, "Featured offer", "A bold poster highlighting our flagship offer with a clear CTA.", "promotion"),
      t(2, "Customer story", "A testimonial card from a happy customer.", "social_proof"),
      t(3, "Tip of the week", "A short educational tip post relevant to our audience.", "education"),
      t(4, "Behind the scenes", "A behind-the-scenes look at our work this week.", "behind_the_scenes"),
      t(5, "Inspiration", "An aspirational lifestyle post in our brand mood.", "inspiration"),
      t(6, "Thank you", "A warm community thank-you post.", "community"),
    ],
  },
];

export function getPlaybook(id: string | null | undefined): IndustryPlaybook {
  return INDUSTRY_PLAYBOOKS.find((p) => p.id === id) || INDUSTRY_PLAYBOOKS[INDUSTRY_PLAYBOOKS.length - 1];
}
