import { useState } from "react";
import { Link } from "react-router-dom";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";
import { useBrand } from "@/hooks/useBrand";
import { useSubscription } from "@/hooks/useSubscription";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { Loader2, Mail, Users, Lock, X, Copy } from "lucide-react";

const TeamMembersPanel = () => {
  const { user } = useAuth();
  const { brand } = useBrand(user);
  const { data: sub } = useSubscription();
  const { toast } = useToast();
  const qc = useQueryClient();

  const teamEnabled = !!sub?.features?.team;
  const isOwner = brand?.__role === "owner";

  const [email, setEmail] = useState("");
  const [role, setRole] = useState<"editor" | "viewer">("editor");
  const [busy, setBusy] = useState(false);

  const { data: members = [], isLoading } = useQuery({
    queryKey: ["brand-team-members", brand?.id],
    queryFn: async () => {
      if (!brand?.id) return [];
      const { data } = await supabase
        .from("brand_team_members")
        .select("*")
        .eq("brand_id", brand.id)
        .order("created_at", { ascending: true });
      return data ?? [];
    },
    enabled: !!brand?.id,
  });

  if (!brand) return null;

  if (!teamEnabled) {
    return (
      <div className="rounded-2xl border border-border bg-card p-6 flex items-center justify-between gap-4">
        <div className="flex items-center gap-3 min-w-0">
          <div className="h-10 w-10 rounded-lg bg-secondary grid place-items-center shrink-0">
            <Lock className="h-4 w-4 text-muted-foreground" />
          </div>
          <div className="min-w-0">
            <p className="font-medium leading-tight">Team Access is on Creator & Agency</p>
            <p className="text-xs text-muted-foreground mt-0.5">
              Invite teammates to collaborate on this brand.
            </p>
          </div>
        </div>
        <Button asChild size="sm" className="rounded-full shrink-0">
          <Link to="/pricing">View plans</Link>
        </Button>
      </div>
    );
  }

  if (!isOwner) {
    return (
      <div className="rounded-2xl border border-border bg-card p-6">
        <p className="text-sm text-muted-foreground">
          Only the brand owner can manage team members.
        </p>
      </div>
    );
  }

  const invite = async () => {
    if (!email.trim() || !brand?.id || !user) return;
    setBusy(true);
    try {
      const trimmed = email.trim().toLowerCase();
      // Insert membership row (invite_token auto-generated by DB default)
      const { data: inserted, error: insErr } = await supabase
        .from("brand_team_members")
        .insert({
          brand_id: brand.id,
          email: trimmed,
          role,
          invited_by: user.id,
          status: "pending",
        } as any)
        .select("invite_token, role")
        .single();

      if (insErr) {
        if (insErr.message?.includes("duplicate")) {
          toast({
            title: "Already invited",
            description: "That email already has a pending or active invite for this brand.",
            variant: "destructive",
          });
          return;
        }
        throw insErr;
      }

      // Fire-and-forget email
      const inviterName =
        (user.user_metadata as any)?.full_name ||
        (user.email ? user.email.split("@")[0] : "A teammate");
      const { error: emailErr } = await supabase.functions.invoke("send-email", {
        body: {
          to: trimmed,
          type: "team_invite",
          data: {
            brand_name: brand.name,
            inviter_name: inviterName,
            token: inserted.invite_token,
            role: inserted.role,
          },
        },
      });
      if (emailErr) console.warn("invite email send failed", emailErr);

      toast({ title: "Invite sent", description: `We emailed ${trimmed}.` });
      setEmail("");
      qc.invalidateQueries({ queryKey: ["brand-team-members", brand.id] });
    } catch (err: any) {
      toast({
        title: "Couldn't send invite",
        description: err.message,
        variant: "destructive",
      });
    } finally {
      setBusy(false);
    }
  };

  const revoke = async (id: string) => {
    const { error } = await supabase
      .from("brand_team_members")
      .delete()
      .eq("id", id);
    if (error) {
      toast({ title: "Couldn't revoke", description: error.message, variant: "destructive" });
      return;
    }
    qc.invalidateQueries({ queryKey: ["brand-team-members", brand.id] });
    toast({ title: "Member removed" });
  };

  const copyInviteLink = (token: string) => {
    const url = `${window.location.origin}/invite/${token}`;
    navigator.clipboard.writeText(url);
    toast({ title: "Invite link copied" });
  };

  return (
    <div className="space-y-4">
      <div className="rounded-2xl border border-border bg-card p-5 space-y-3">
        <div className="flex items-center gap-2">
          <Users className="h-4 w-4 text-muted-foreground" />
          <h3 className="text-sm font-medium">Invite a teammate</h3>
        </div>
        <div className="flex flex-col sm:flex-row gap-2">
          <Input
            type="email"
            placeholder="teammate@email.com"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            className="h-11 flex-1"
          />
          <Select value={role} onValueChange={(v) => setRole(v as "editor" | "viewer")}>
            <SelectTrigger className="h-11 w-full sm:w-32">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="editor">Editor</SelectItem>
              <SelectItem value="viewer">Viewer</SelectItem>
            </SelectContent>
          </Select>
          <Button
            onClick={invite}
            disabled={!email.trim() || busy}
            className="rounded-full h-11 gap-1.5"
          >
            {busy ? <Loader2 className="h-4 w-4 animate-spin" /> : <Mail className="h-4 w-4" />}
            Send invite
          </Button>
        </div>
        <p className="text-xs text-muted-foreground">
          Editors can create and edit content. Viewers can read everything but won't edit (UI-enforced for now).
        </p>
      </div>

      <div className="rounded-2xl border border-border bg-card divide-y divide-border">
        {isLoading ? (
          <div className="p-5 text-sm text-muted-foreground flex items-center gap-2">
            <Loader2 className="h-4 w-4 animate-spin" /> Loading members…
          </div>
        ) : members.length === 0 ? (
          <div className="p-5 text-sm text-muted-foreground">No teammates yet.</div>
        ) : (
          members.map((m: any) => (
            <div key={m.id} className="flex items-center justify-between gap-3 p-4">
              <div className="min-w-0">
                <p className="font-medium truncate text-sm">{m.email}</p>
                <p className="text-xs text-muted-foreground">
                  {m.role} ·{" "}
                  <span
                    className={
                      m.status === "active"
                        ? "text-primary"
                        : m.status === "pending"
                        ? "text-amber-600"
                        : "text-destructive"
                    }
                  >
                    {m.status}
                  </span>
                </p>
              </div>
              <div className="flex items-center gap-1 shrink-0">
                {m.status === "pending" && m.invite_token && (
                  <Button
                    size="sm"
                    variant="ghost"
                    onClick={() => copyInviteLink(m.invite_token)}
                    className="rounded-full"
                    title="Copy invite link"
                  >
                    <Copy className="h-4 w-4" />
                  </Button>
                )}
                <Button
                  size="sm"
                  variant="ghost"
                  onClick={() => revoke(m.id)}
                  className="rounded-full text-destructive hover:text-destructive"
                  title="Remove"
                >
                  <X className="h-4 w-4" />
                </Button>
              </div>
            </div>
          ))
        )}
      </div>
    </div>
  );
};

export default TeamMembersPanel;
